# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_acme_error:
    pattern:  /error
    defaults: { _controller: AcmeErrorBundle:Default:index }